AXI muckbucket: axi_responder_seq Class Reference
axi_responder_seq Class Reference abstract
Forever running sequence that setups up responder *ready toggle patterns, then receives TLM packet from monitor and sends to responder.
Public Member Functions
uvm_object_utils(axi_responder_seq) uvm_declare_p_sequencer(axi_sequencer) logic<7 new (string name="axi_responder_seq")
Constructor.
task body ()
Does all the work.
uvm_object_utils (axi_seq) int xfers_done=0
void response_handler (uvm_sequence_item response)
Public Attributes
memory m_memory
Detailed Description
Forever running sequence that setups up responder *ready toggle patterns, then receives TLM packet from monitor and sends to responder.
Definition at line 23 of file axi_responder_seq.svh.
Member Function Documentation
task axi_responder_seq::body ()
Does all the work.
Creates constrained random awready toggle pattern
Sends it
Creates constrained random wready toggle pattern
Sends it
Creates constrained random arready toggle pattern
Sends it
In a forever loop, waits for TLM packets from monitor sends them on to responder
Definition at line 56 of file axi_responder_seq.svh.
References axi_seq_item::convert2string(), e_SETARREADYTOGGLEPATTERN, e_SETAWREADYTOGGLEPATTERN, and e_SETWREADYTOGGLEPATTERN.
axi_responder_seq::new (string name = "axi_responder_seq")
Constructor.
Doesn't actually do anything except call parent constructor
Definition at line 40 of file axi_responder_seq.svh.
References new().
Referenced by axi_base_test::new(), and new().
void axi_seq::response_handler (uvm_sequence_item response) inherited
Definition at line 40 of file axi_seq.svh.
axi_seq::uvm_object_utils (axi_seq) pure virtual inherited
Member Data Documentation
memory axi_seq::m_memory inherited
Definition at line 31 of file axi_seq.svh.
Referenced by axi_seq::body().
The documentation for this class was generated from the following file:
tb/axi_responder_seq.svh