AXI muckbucket: axi_monitor Class Reference
axi_monitor Class Reference
monitors all 5 channels for activity
Public Member Functions
uvm_component_utils (axi_monitor) uvm_analysis_port< axi_seq_item > ap
new (string name="axi_monitor", uvm_component parent=null)
Constructor.
void build_phase (uvm_phase phase)
Creates the analysis port and virtual interface.
void connect_phase (uvm_phase phase)
task run_phase (uvm_phase phase)
Starts the monitoring threads.
task monitor_write_address ()
monitors Write Address channel
task monitor_write_data ()
monitors Write Data channel
task monitor_write_response ()
monitors Write Response channel and sends out TLM pkt Loop Wait for activity on the Write Response Channel Convert into an axi_seq_item Send out analysis port
task monitor_read_address ()
monitors Read Address channel
task monitor_read_data ()
monitors Read Data channel and sends out TLM pkt Loop Wait for activity on the Read Data Channel,store in queue Once read address packet received, store queue contents into tlm pkt When rlast received, send out analysis port
uvm_component_utils (axi_monitor) uvm_analysis_port< axi_seq_item > ap
new (string name="axi_monitor", uvm_component parent=null)
void build_phase (uvm_phase phase)
void connect_phase (uvm_phase phase)
task run_phase (uvm_phase phase)
task write_address ()
monitors Write Address channel
task write_data ()
monitors Write Data channel
task write_response ()
monitors Write Response channel and sends out TLM pkt Loop Wait for activity on the Write Response Channel Convert into an axi_seq_item Send out analysis port
task read_address ()
monitors Read Address channel
task read_data ()
monitors Read Data channel and sends out TLM pkt Loop Wait for activity on the Read Data Channel,store in queue Once read address packet received, store queue contents into tlm pkt When rlast received, send out analysis port
Public Attributes
uvm_analysis_port< axi_seq_item > driver_activity_ap
axi_seq_item_w_vector_s w_q [$]
axi_seq_item_r_vector_s r_q [$]
mailbox< axi_seq_item > aw_mbx = new(0)
mailbox< axi_seq_item > ar_mbx = new(0)
axi_if_abstract vif
axi_agent_config m_config
memory m_memory
mailbox< axi_seq_item > writedata_mbx = new(0)
mailbox< axi_seq_item > readdata_mbx = new(0)
Detailed Description
monitors all 5 channels for activity
Sends Write Address, Write Response and Read Address out on each clock
Sends entire Write Data and Read Data out together
Driver
* Updates agent memory on each write data beat
Responder
* Sends a read data sequence to the responder when a read address transaction is detected Main cover properties and assertions are here.
Definition at line 33 of file axi_monitor.svh.
Member Function Documentation
void axi_monitor::build_phase (uvm_phase phase)
void axi_monitor::build_phase (uvm_phase phase)
Creates the analysis port and virtual interface.
Definition at line 74 of file axi_monitor.svh.
References driver_activity_ap, and vif.
void axi_monitor::connect_phase (uvm_phase phase)
void axi_monitor::connect_phase (uvm_phase phase)
Definition at line 87 of file axi_monitor.svh.
task axi_monitor::monitor_read_address ()
monitors Read Address channel
and sends out TLM pkt. If this monitor's agent is a responder, then also creates another TLM packet for Read Data channel monitoring thread to use to send back to the master Loop Wait for activity on the Write Address Channel Convert into an axi_seq_item Send out analysis port If responder, read from agent's memory, create another TLM packet and send to Read Data channel to send back to master
Definition at line 299 of file axi_monitor.svh.
References axi_seq_item::addr, ar_mbx, ar_to_class(), axi_seq_item::burst_size, axi_seq_item::burst_type, calculate_axlen(), axi_seq_item::cmd, axi_seq_item::convert2string(), axi_seq_item::data, driver_activity_ap, axi_agent_config::drv_type, e_READ, e_READ_DATA, e_RESPONDER, get_beat_N_byte_lanes(), axi_if_abstract::get_data_bus_width(), get_next_address(), axi_seq_item::len, m_config, m_memory, memory::read(), read_data(), axi_seq_item::valid, vif, and axi_if_abstract::wait_for_read_address().
Referenced by run_phase().
task axi_monitor::monitor_read_data ()
monitors Read Data channel and sends out TLM pkt Loop Wait for activity on the Read Data Channel,store in queue Once read address packet received, store queue contents into tlm pkt When rlast received, send out analysis port
Definition at line 454 of file axi_monitor.svh.
References ar_mbx, axi_seq_item::cmd, axi_seq_item::data, e_READ_DATA, axi_seq_item::len, r_q, axi_seq_item_r_vector_s::rlast, vif, and axi_if_abstract::wait_for_read_data().
Referenced by run_phase().
task axi_monitor::monitor_write_address ()
monitors Write Address channel
and sends out TLM pkt. If this monitor's agent is a responder, then also creates another TLM packet for Write Data channel monitoring thread to use Loop Wait for activity on the Write Address Channel Convert into an axi_seq_item Send out analysis port Add to Write Data Channel monitoring thread's queue
Definition at line 103 of file axi_monitor.svh.
References aw_mbx, aw_to_class(), axi_seq_item::cmd, axi_seq_item::convert2string(), e_WRITE, axi_seq_item::len, vif, and axi_if_abstract::wait_for_write_address().
Referenced by run_phase().
task axi_monitor::monitor_write_data ()
monitors Write Data channel
and sends out TLM pkt. Loop Wait for activity on the Write Data Channel and push it into a queue When a write address isavailable,
pop all queued write data into the write address packet.
write to m_memory (likely the agent's local memory memory instantiation Once number of expected beats is received (matches awlen), then send out analysis port
Definition at line 145 of file axi_monitor.svh.
References axi_seq_item::addr, aw_mbx, axi_seq_item::burst_size, axi_seq_item::burst_type, axi_seq_item::cmd, axi_seq_item::data, driver_activity_ap, axi_agent_config::drv_type, e_RESPONDER, e_WRITE_DATA, e_WRITE_RESPONSE, get_beat_N_byte_lanes(), axi_if_abstract::get_data_bus_width(), get_next_address(), axi_seq_item::len, m_config, m_memory, vif, w_q, axi_if_abstract::wait_for_write_data(), axi_seq_item_w_vector_s::wdata, axi_seq_item_w_vector_s::wlast, memory::write(), axi_seq_item::wstrb, and axi_seq_item_w_vector_s::wstrb.
Referenced by run_phase().
task axi_monitor::monitor_write_response ()
monitors Write Response channel and sends out TLM pkt Loop Wait for activity on the Write Response Channel Convert into an axi_seq_item Send out analysis port
Definition at line 266 of file axi_monitor.svh.
References b_to_class(), axi_seq_item::cmd, e_WRITE_RESPONSE, vif, and axi_if_abstract::wait_for_write_response().
Referenced by run_phase().
axi_monitor::new (string name = "axi_monitor", uvm_component parent = null)
axi_monitor::new (string name = "axi_monitor", uvm_component parent = null)
Constructor.
Definition at line 70 of file axi_monitor.svh.
task axi_monitor::read_address ()
monitors Read Address channel
and sends out TLM pkt. If this monitor's agent is a responder, then also creates another TLM packet for Read Data channel monitoring thread to use to send back to the master Loop Wait for activity on the Write Address Channel Convert into an axi_seq_item Send out analysis port If responder, read from agent's memory, create another TLM packet and send to Read Data channel to send back to master
Definition at line 308 of file axi_monitor.svh.
References axi_seq_item::addr, ADDR_WIDTH, ar_to_class(), axi_seq_item::burst_size, axi_seq_item::burst_type, calculate_axlen(), axi_seq_item::cmd, axi_seq_item::convert2string(), axi_seq_item::data, driver_activity_ap, axi_agent_config::drv_type, e_READ, e_READ_DATA, e_RESPONDER, get_beat_N_byte_lanes(), axi_if_abstract::get_data_bus_width(), get_next_address(), axi_seq_item::len, m_config, m_memory, memory::read(), read_data(), readdata_mbx, axi_seq_item::valid, vif, and axi_if_abstract::wait_for_read_address().
task axi_monitor::read_data ()
monitors Read Data channel and sends out TLM pkt Loop Wait for activity on the Read Data Channel,store in queue Once read address packet received, store queue contents into tlm pkt When rlast received, send out analysis port
Definition at line 458 of file axi_monitor.svh.
References axi_seq_item::cmd, axi_seq_item::data, e_READ_DATA, axi_seq_item::len, r_q, readdata_mbx, axi_seq_item_r_vector_s::rlast, vif, and axi_if_abstract::wait_for_read_data().
Referenced by monitor_read_address(), and read_address().
task axi_monitor::run_phase (uvm_phase phase)
task axi_monitor::run_phase (uvm_phase phase)
Starts the monitoring threads.
Definition at line 515 of file axi_monitor.svh.
References monitor_read_address(), monitor_read_data(), monitor_write_address(), monitor_write_data(), and monitor_write_response().
axi_monitor::uvm_component_utils (axi_monitor)
axi_monitor::uvm_component_utils (axi_monitor)
task axi_monitor::write_address ()
monitors Write Address channel
and sends out TLM pkt. If this monitor's agent is a responder, then also creates another TLM packet for Write Data channel monitoring thread to use Loop Wait for activity on the Write Address Channel Convert into an axi_seq_item Send out analysis port Add to Write Data Channel monitoring thread's queue
Definition at line 108 of file axi_monitor.svh.
References aw_to_class(), axi_seq_item::cmd, axi_seq_item::convert2string(), driver_activity_ap, axi_agent_config::drv_type, e_RESPONDER, e_WRITE, axi_seq_item::len, m_config, vif, axi_if_abstract::wait_for_write_address(), and writedata_mbx.
task axi_monitor::write_data ()
monitors Write Data channel
and sends out TLM pkt. Loop Wait for activity on the Write Data Channel and push it into a queue When a write address isavailable,
pop all queued write data into the write address packet.
write to m_memory (likely the agent's local memory memory instantiation Once number of expected beats is received (matches awlen), then send out analysis port
Definition at line 161 of file axi_monitor.svh.
References axi_seq_item::addr, ADDR_WIDTH, axi_seq_item::burst_size, axi_seq_item::burst_type, axi_seq_item::cmd, axi_seq_item::data, axi_agent_config::drv_type, e_RESPONDER, e_WRITE_DATA, get_beat_N_byte_lanes(), axi_if_abstract::get_data_bus_width(), get_next_address(), axi_seq_item::len, m_config, m_memory, vif, w_q, axi_if_abstract::wait_for_write_data(), axi_seq_item_w_vector_s::wdata, axi_seq_item_w_vector_s::wlast, memory::write(), writedata_mbx, axi_seq_item::wstrb, and axi_seq_item_w_vector_s::wstrb.
task axi_monitor::write_response ()
monitors Write Response channel and sends out TLM pkt Loop Wait for activity on the Write Response Channel Convert into an axi_seq_item Send out analysis port
Definition at line 275 of file axi_monitor.svh.
References b_to_class(), axi_seq_item::cmd, e_WRITE_RESPONSE, vif, and axi_if_abstract::wait_for_write_response().
Member Data Documentation
mailbox<axi_seq_item> axi_monitor::ar_mbx = new(0)
Definition at line 47 of file axi_monitor.svh.
Referenced by monitor_read_address(), and monitor_read_data().
mailbox<axi_seq_item> axi_monitor::aw_mbx = new(0)
Definition at line 46 of file axi_monitor.svh.
Referenced by monitor_write_address(), and monitor_write_data().
uvm_analysis_port< axi_seq_item > axi_monitor::driver_activity_ap
Definition at line 38 of file axi_monitor.svh.
Referenced by build_phase(), axi_agent::connect_phase(), monitor_read_address(), monitor_write_data(), read_address(), and write_address().
axi_agent_config axi_monitor::m_config
Definition at line 50 of file axi_monitor.svh.
Referenced by axi_agent::build_phase(), monitor_read_address(), monitor_write_data(), read_address(), write_address(), and write_data().
memory axi_monitor::m_memory
Definition at line 51 of file axi_monitor.svh.
Referenced by axi_agent::build_phase(), monitor_read_address(), monitor_write_data(), read_address(), and write_data().
axi_seq_item_r_vector_s axi_monitor::r_q[$]
Definition at line 42 of file axi_monitor.svh.
Referenced by monitor_read_data(), and read_data().
mailbox<axi_seq_item> axi_monitor::readdata_mbx = new(0)
Definition at line 44 of file axi_monitor.svh.
Referenced by read_address(), and read_data().
axi_if_abstract axi_monitor::vif
Definition at line 49 of file axi_monitor.svh.
Referenced by build_phase(), monitor_read_address(), monitor_read_data(), monitor_write_address(), monitor_write_data(), monitor_write_response(), read_address(), read_data(), write_address(), write_data(), and write_response().
axi_seq_item_w_vector_s axi_monitor::w_q[$]
Definition at line 41 of file axi_monitor.svh.
Referenced by monitor_write_data(), and write_data().
mailbox<axi_seq_item> axi_monitor::writedata_mbx = new(0)
Definition at line 43 of file axi_monitor.svh.
Referenced by write_address(), and write_data().
The documentation for this class was generated from the following file:
result_from_tec101/tb/tb/axi_monitor.svh