AXI muckbucket: axi_master_driver Class Reference
axi_master_driver Class Reference
Public Member Functions
uvm_component_utils (axi_master_driver) axi_if_abstract vif
new (string name="axi_master_driver", uvm_component parent=null)
void build_phase (uvm_phase phase)
void connect_phase (uvm_phase phase)
void end_of_elaboration_phase (uvm_phase phase)
task run_phase (uvm_phase phase)
task write (ref axi_seq_item item)
Detailed Description
Definition at line 1 of file axi_master_driver.svh.
Member Function Documentation
void axi_master_driver::build_phase (uvm_phase phase)
Definition at line 25 of file axi_master_driver.svh.
void axi_master_driver::connect_phase (uvm_phase phase)
Definition at line 32 of file axi_master_driver.svh.
void axi_master_driver::end_of_elaboration_phase (uvm_phase phase)
Definition at line 36 of file axi_master_driver.svh.
axi_master_driver::new (string name = "axi_master_driver", uvm_component parent = null)
Definition at line 18 of file axi_master_driver.svh.
task axi_master_driver::run_phase (uvm_phase phase)
Definition at line 40 of file axi_master_driver.svh.
References axi_seq_item::addr, axi_seq_item::cmd, axi_seq_item::convert2string(), axi_seq_item::data, and write().
axi_master_driver::uvm_component_utils (axi_master_driver)
task axi_master_driver::write (ref axi_seq_item item)
Definition at line 63 of file axi_master_driver.svh.
Referenced by run_phase().
The documentation for this class was generated from the following file:
tb/axi_master_driver.svh