AXI muckbucket: axi_seq_item Class Reference
axi_seq_item Class Reference
contains all data and functions related to axi and usage
Public Member Functions
constraint max_len ()
constraint valid_c ()
constraint data_c ()
constraint wstrb_c ()
constraint wlast_c ()
new (string name="axi_seq_item")
Constructor.
string convert2string ()
Convert item's variable into one printable string.
void do_copy (uvm_object rhs)
Deep copy.
bit do_compare (uvm_object rhs, uvm_comparer comparer)
Deep compare.
void do_print (uvm_printer printer)
prints out immediate object, but no parents' stuff.
void post_randomize ()
Tweak things after randomization.
bit< 63:0 > calculate_aligned_address (input bit< 63:0 > addr, input int number_bytes)
Calculate aligned address from current address.
int calculate_beats (input bit< 63:0 > addr, input int number_bytes, input int burst_length)
Calculate number of beats/clks in this burst.
void update_address ()
Update AXI item's address.
void initialize ()
Initialize all variables after item creation, whether random or manually set.
void update ()
Update the aligned address and used byte lanes on each beat.
void aw_from_class (ref axi_seq_item t, output axi_seq_item_aw_vector_s v)
Pull values out of axi_seq_item and stuff into a axi_seq_item_aw_vector_s.
void ar_from_class (ref axi_seq_item t, output axi_seq_item_ar_vector_s v)
take values from an axi_seq_item and stuff into a axi_seq_item_ar_vector_s
Static Public Member Functions
static void aw_to_class (ref axi_seq_item t, input axi_seq_item_aw_vector_s v)
Pull values out of a axi_seq_item_aw_vector_s and stuffs them into an axi_seq_item.
static void w_from_class (input[31:0] wdata, input[4] wstrb, input wvalid, input wlast, output axi_seq_item_w_vector_s v)
take values from write data channel and stuff into a axi_seq_item_w_vector_s
static void w_to_class (output[31:0] wdata, output[4] wstrb, output wvalid, output wlast, input axi_seq_item_w_vector_s v)
take values from a axi_seq_item_w_vector_s
static void b_from_class (input[6] bid, input[2] bresp, output axi_seq_item_b_vector_s v)
take values from write response channel and stuff into a axi_seq_item_b_vector_s
static void b_to_class (ref axi_seq_item t, input axi_seq_item_b_vector_s v)
return values from a axi_seq_item_b_vector_s and return an axi_seq_item
static void ar_to_class (ref axi_seq_item t, input axi_seq_item_ar_vector_s v)
Pull values out of a axi_seq_item_ar_vector_s and stuffs them into an axi_seq_item.
Public Attributes
uvm_object_utils(axi_seq_item) rand bit< 6 rand bit< 63:0 > addr
rand bit valid []
rand bit< 7:0 > data []
rand bit wstrb []
rand bit wlast []
rand int len =0
logic< 7:0 > awlen
rand logic< 2:0 > burst_size
rand logic< 1:0 > burst_type
logic< 0:0 > lock = 0x0
logic< 3:0 > cache = 0x0
logic< 2:0 > prot = 0x0
logic< 3:0 > qos = 0x0
logic< 6-1:0 > bid = 0xF
logic< 1:0 > bresp = 0x3
rand cmd_t cmd
rand logic< 31:0 > toggle_pattern = 0xFFFF_FFFF
bit< 63:0 > Start_Address
bit< 63:0 > Aligned_Address
bit aligned
int Number_Bytes
int iNumber_Bytes
int Burst_Length_Bytes
int Data_Bus_Bytes
bit< 63:0 > Lower_Wrap_Boundary
bit< 63:0 > Upper_Wrap_Boundary
int Lower_Byte_Lane
int Upper_Byte_Lane
bit< 1:0 > Mode
int dtsize
int n =0
int validcntr
int validcntr_max
int dataoffset =0
int initialized =0
const int c_AXI3_MAXBEATCNT =16
const int c_AXI4_MAXBEATCNT =256
Detailed Description
contains all data and functions related to axi and usage
In addition to variables like addr,len, id, this alsocontains functions that could be moved into axi_uvm_pkg to save object space. Things like calculating aligned_address from address.
Definition at line 34 of file axi_seq_item.svh.
Member Function Documentation
void axi_seq_item::ar_from_class (ref axi_seq_item t, output axi_seq_item_ar_vector_s v)
take values from an axi_seq_item and stuff into a axi_seq_item_ar_vector_s
This funcion returns a ready-to-be used struct so arlen and araddr are calcuated in this function.
Parameters
t - The axi_seq_item is passed by reference
Returns
v - packed struct of type axi_seq_item_ar_vector_s
Definition at line 647 of file axi_seq_item.svh.
References addr, axi_seq_item_ar_vector_s::araddr, axi_seq_item_ar_vector_s::arburst, axi_seq_item_ar_vector_s::arcache, axi_seq_item_ar_vector_s::arid, axi_seq_item_ar_vector_s::arlen, axi_seq_item_ar_vector_s::arlock, axi_seq_item_ar_vector_s::arprot, axi_seq_item_ar_vector_s::arqos, axi_seq_item_ar_vector_s::arsize, calculate_aligned_address(), calculate_beats(), and len.
Referenced by axi_driver::read_address(), and wlast_c().
void axi_seq_item::ar_to_class (ref axi_seq_item t, input axi_seq_item_ar_vector_s v) static
Pull values out of a axi_seq_item_ar_vector_s and stuffs them into an axi_seq_item.
t.len is converted from arlen into a byte len. It uses burst_size (bytes per beat) * beats_per_burst to give a maximum byte length.
Parameters
t - an axi_seq_item
Returns
v - a packed struct of type axi_seq_item_ar_vector_s
Definition at line 677 of file axi_seq_item.svh.
References axi_seq_item_ar_vector_s::araddr, axi_seq_item_ar_vector_s::arburst, axi_seq_item_ar_vector_s::arcache, axi_seq_item_ar_vector_s::arid, axi_seq_item_ar_vector_s::arlen, axi_seq_item_ar_vector_s::arlock, axi_seq_item_ar_vector_s::arprot, axi_seq_item_ar_vector_s::arqos, and axi_seq_item_ar_vector_s::arsize.
Referenced by axi_monitor::monitor_read_address(), and wlast_c().
void axi_seq_item::aw_from_class (ref axi_seq_item t, output axi_seq_item_aw_vector_s v)
Pull values out of axi_seq_item and stuff into a axi_seq_item_aw_vector_s.
This funcion returns a ready-to-be used struct so awlen and awaddr are calcuated in this function.
Parameters
t an axi_seq_item
Returns
v a packed struct of type axi_seq_item_aw_vector_s
Definition at line 497 of file axi_seq_item.svh.
References addr, axi_seq_item_aw_vector_s::awaddr, axi_seq_item_aw_vector_s::awburst, axi_seq_item_aw_vector_s::awcache, axi_seq_item_aw_vector_s::awid, axi_seq_item_aw_vector_s::awlen, axi_seq_item_aw_vector_s::awlock, axi_seq_item_aw_vector_s::awprot, axi_seq_item_aw_vector_s::awqos, axi_seq_item_aw_vector_s::awsize, calculate_aligned_address(), calculate_beats(), and len.
Referenced by wlast_c(), and axi_driver::write_address().
void axi_seq_item::aw_to_class (ref axi_seq_item t, input axi_seq_item_aw_vector_s v) static
Pull values out of a axi_seq_item_aw_vector_s and stuffs them into an axi_seq_item.
t.len is converted from awlen into a byte len. It uses burst_size (bytes per beat) * beats_per_burst to give a maximum byte length.
Returns
t an axi_seq_item
Parameters
v a packed struct of type axi_seq_item_aw_vector_s
Definition at line 527 of file axi_seq_item.svh.
References axi_seq_item_aw_vector_s::awaddr, axi_seq_item_aw_vector_s::awburst, axi_seq_item_aw_vector_s::awcache, axi_seq_item_aw_vector_s::awid, axi_seq_item_aw_vector_s::awlen, axi_seq_item_aw_vector_s::awlock, axi_seq_item_aw_vector_s::awprot, axi_seq_item_aw_vector_s::awqos, and axi_seq_item_aw_vector_s::awsize.
Referenced by axi_monitor::monitor_write_address(), and wlast_c().
void axi_seq_item::b_from_class (inputbid [6], inputbresp [2], output axi_seq_item_b_vector_s v) static
take values from write response channel and stuff into a axi_seq_item_b_vector_s
Parameters
bid - Write Response ID tag
bresp - Write Response
Returns
v - packed struct of type axi_seq_item_b_vector_s
Definition at line 608 of file axi_seq_item.svh.
References bid, axi_seq_item_b_vector_s::bid, bresp, and axi_seq_item_b_vector_s::bresp.
Referenced by wlast_c().
void axi_seq_item::b_to_class (ref axi_seq_item t, input axi_seq_item_b_vector_s v) static
return values from a axi_seq_item_b_vector_s and return an axi_seq_item
Parameters
v - packed struct of type axi_seq_item_b_vector_s
Returns
t - an axi_seq_item
Definition at line 626 of file axi_seq_item.svh.
References axi_seq_item_b_vector_s::bid, and axi_seq_item_b_vector_s::bresp.
Referenced by axi_monitor::monitor_write_response(), and wlast_c().
bit< 63:0 > axi_seq_item::calculate_aligned_address (input bit< 63:0 > addr, input int number_bytes)
Calculate aligned address from current address.
Used to guarantee transfers are aligned on the bus for most efficient bus usage
Definition at line 442 of file axi_seq_item.svh.
Referenced by ar_from_class(), aw_from_class(), calculate_beats(), and wlast_c().
int axi_seq_item::calculate_beats (input bit< 63:0 > addr, input int number_bytes, input int burst_length)
Calculate number of beats/clks in this burst.
If the transfer is too large, this function will return a bogus result The caller is responsible for insuring safety.
Todo:
: check if size (length + address-misalignment) is too large
Definition at line 465 of file axi_seq_item.svh.
References addr, and calculate_aligned_address().
Referenced by ar_from_class(), aw_from_class(), and wlast_c().
string axi_seq_item::convert2string ()
Convert item's variable into one printable string.
Definition at line 206 of file axi_seq_item.svh.
References addr, aligned, Aligned_Address, bid, bresp, Burst_Length_Bytes, burst_size, burst_type, cmd, data, Data_Bus_Bytes, dtsize, iNumber_Bytes, len, Lower_Byte_Lane, Lower_Wrap_Boundary, Mode, Number_Bytes, Start_Address, Upper_Byte_Lane, and Upper_Wrap_Boundary.
Referenced by axi_responder_seq::body(), axi_seq::body(), do_print(), axi_monitor::monitor_read_address(), axi_monitor::monitor_write_address(), axi_driver::read_data(), axi_driver::run_phase(), axi_responder::run_phase(), wlast_c(), axi_coveragecollector::write(), axi_scoreboard::write(), axi_driver::write_address(), axi_driver::write_data(), axi_responder::write_data(), and axi_responder::write_response().
constraint axi_seq_item::data_c () inline
Definition at line 121 of file axi_seq_item.svh.
References data, and len.
bit axi_seq_item::do_compare (uvm_object rhs, uvm_comparer comparer)
Deep compare.
Compare everything
Todo:
: This function needs some attention.
Definition at line 282 of file axi_seq_item.svh.
References addr, data, and len.
Referenced by wlast_c().
void axi_seq_item::do_copy (uvm_object rhs)
Deep copy.
Deep copy everything
Definition at line 247 of file axi_seq_item.svh.
References addr, bid, bresp, burst_size, burst_type, cache, cmd, data, len, lock, prot, qos, valid, wlast, and wstrb.
Referenced by wlast_c().
void axi_seq_item::do_print (uvm_printer printer)
prints out immediate object, but no parents' stuff.
Definition at line 305 of file axi_seq_item.svh.
References convert2string().
Referenced by wlast_c().
void axi_seq_item::initialize ()
Initialize all variables after item creation, whether random or manually set.
All variables that rely on those initial settings but are otherwise static are set/updated in this function. This function is meant to be called once per burst.
Definition at line 387 of file axi_seq_item.svh.
References addr, aligned, Aligned_Address, Burst_Length_Bytes, burst_size, burst_type, Data_Bus_Bytes, dataoffset, dtsize, e_WRAP, initialized, len, Lower_Wrap_Boundary, Mode, Number_Bytes, Start_Address, update(), Upper_Wrap_Boundary, valid, validcntr, and validcntr_max.
Referenced by axi_monitor::monitor_read_address(), axi_monitor::monitor_read_data(), axi_monitor::monitor_write_data(), axi_driver::read_data(), axi_responder::read_data(), wlast_c(), and axi_driver::write_data().
constraint axi_seq_item::max_len () inline
Definition at line 104 of file axi_seq_item.svh.
References burst_size, e_SETARREADYTOGGLEPATTERN, e_SETAWREADYTOGGLEPATTERN, and e_SETWREADYTOGGLEPATTERN.
axi_seq_item::new (string name = "axi_seq_item")
Constructor.
Doesn't actually do anything except call parent constructor
Definition at line 199 of file axi_seq_item.svh.
void axi_seq_item::post_randomize ()
Tweak things after randomization.
Currenly being used to reset the data[] to incrementing pattern ending with 'FE. This is for easier debugging. More love coming.
Definition at line 315 of file axi_seq_item.svh.
References data, len, valid, wlast, and wstrb.
Referenced by wlast_c().
void axi_seq_item::update ()
Update the aligned address and used byte lanes on each beat.
Aligned address and used byte lanes change per beat. That is handled in this function.This function is meant to be called every beat.
Definition at line 419 of file axi_seq_item.svh.
References addr, aligned, Aligned_Address, Data_Bus_Bytes, iNumber_Bytes, Lower_Byte_Lane, Number_Bytes, and Upper_Byte_Lane.
Referenced by initialize(), update_address(), and wlast_c().
void axi_seq_item::update_address ()
Update AXI item's address.
Updates address after every beat. Address changes depending on if it's a partial transfer, width of bus, fixed vs incrementing vs wrapped.
Definition at line 363 of file axi_seq_item.svh.
References addr, aligned, Aligned_Address, e_FIXED, e_WRAP, Lower_Wrap_Boundary, Mode, Number_Bytes, update(), and Upper_Wrap_Boundary.
Referenced by axi_monitor::monitor_read_data(), axi_monitor::monitor_write_data(), axi_driver::read_data(), axi_responder::read_data(), wlast_c(), and axi_driver::write_data().
constraint axi_seq_item::valid_c () inline
Definition at line 119 of file axi_seq_item.svh.
References len, and valid.
void axi_seq_item::w_from_class (inputwdata [31:0], inputwstrb [4], input wvalid, input wlast, output axi_seq_item_w_vector_s v) static
take values from write data channel and stuff into a axi_seq_item_w_vector_s
Todo:
: this funct isn't from a class so rename.
Parameters
wdata - Write data value
wstrb - Write strobe
wvalid - Write Valid
wlast - wlast (last beat of write burst)
Returns
v - a packed struct.
Definition at line 558 of file axi_seq_item.svh.
References axi_seq_item_w_vector_s::wdata, wlast, axi_seq_item_w_vector_s::wlast, wstrb, axi_seq_item_w_vector_s::wstrb, and axi_seq_item_w_vector_s::wvalid.
Referenced by wlast_c().
void axi_seq_item::w_to_class (outputwdata [31:0], outputwstrb [4], output wvalid, output wlast, input axi_seq_item_w_vector_s v) static
take values from a axi_seq_item_w_vector_s
Todo:
: this funct isn't from a class so rename.
Returns
wdata - Write data value
wstrb - Write strobe
wvalid - Write Valid
wlast - wlast (last beat of write burst)
Parameters
v - a packed struct.
Definition at line 584 of file axi_seq_item.svh.
References axi_seq_item_w_vector_s::wdata, axi_seq_item_w_vector_s::wlast, axi_seq_item_w_vector_s::wstrb, and axi_seq_item_w_vector_s::wvalid.
Referenced by wlast_c().
constraint axi_seq_item::wlast_c () inline
Definition at line 125 of file axi_seq_item.svh.
References addr, ar_from_class(), ar_to_class(), aw_from_class(), aw_to_class(), b_from_class(), b_to_class(), bid, bresp, calculate_aligned_address(), calculate_beats(), convert2string(), do_compare(), do_copy(), do_print(), initialize(), len, post_randomize(), update(), update_address(), w_from_class(), w_to_class(), wlast, and wstrb.
constraint axi_seq_item::wstrb_c () inline
Definition at line 123 of file axi_seq_item.svh.
References len, and wstrb.
Member Data Documentation
uvm_object_utils (axi_seq_item) rand bit <6 rand bit<63:0> axi_seq_item::addr
Definition at line 35 of file axi_seq_item.svh.
Referenced by ar_from_class(), aw_from_class(), axi_seq::body(), calculate_beats(), convert2string(), do_compare(), do_copy(), initialize(), update(), update_address(), and wlast_c().
bit axi_seq_item::aligned
Definition at line 81 of file axi_seq_item.svh.
Referenced by convert2string(), initialize(), update(), and update_address().
bit<63:0> axi_seq_item::Aligned_Address
Definition at line 80 of file axi_seq_item.svh.
Referenced by convert2string(), initialize(), update(), and update_address().
logic<7:0> axi_seq_item::awlen
Definition at line 51 of file axi_seq_item.svh.
logic<6-1:0> axi_seq_item::bid = 0xF
Definition at line 60 of file axi_seq_item.svh.
Referenced by b_from_class(), convert2string(), do_copy(), wlast_c(), and axi_driver::write_response().
logic<1:0> axi_seq_item::bresp = 0x3
Definition at line 61 of file axi_seq_item.svh.
Referenced by b_from_class(), convert2string(), do_copy(), wlast_c(), and axi_driver::write_response().
int axi_seq_item::Burst_Length_Bytes
Definition at line 84 of file axi_seq_item.svh.
Referenced by convert2string(), initialize(), axi_responder::read_data(), and axi_driver::write_data().
rand logic<2:0> axi_seq_item::burst_size
Definition at line 52 of file axi_seq_item.svh.
Referenced by axi_seq::body(), convert2string(), do_copy(), initialize(), and max_len().
rand logic<1:0> axi_seq_item::burst_type
Definition at line 53 of file axi_seq_item.svh.
Referenced by axi_seq::body(), convert2string(), do_copy(), and initialize().
const int axi_seq_item::c_AXI3_MAXBEATCNT =16
Definition at line 101 of file axi_seq_item.svh.
const int axi_seq_item::c_AXI4_MAXBEATCNT =256
Definition at line 102 of file axi_seq_item.svh.
logic<3:0> axi_seq_item::cache = 0x0
Definition at line 56 of file axi_seq_item.svh.
Referenced by do_copy().
rand cmd_t axi_seq_item::cmd
Definition at line 63 of file axi_seq_item.svh.
Referenced by convert2string(), do_copy(), axi_monitor::monitor_read_address(), axi_monitor::monitor_read_data(), axi_monitor::monitor_write_address(), axi_monitor::monitor_write_data(), axi_monitor::monitor_write_response(), axi_driver::run_phase(), axi_responder::run_phase(), and axi_scoreboard::write().
rand bit<7:0> axi_seq_item::data[]
Definition at line 45 of file axi_seq_item.svh.
Referenced by axi_seq::body(), convert2string(), data_c(), do_compare(), do_copy(), axi_monitor::monitor_read_address(), axi_monitor::monitor_read_data(), axi_monitor::monitor_write_data(), post_randomize(), axi_driver::read_data(), axi_responder::read_data(), and axi_driver::write_data().
int axi_seq_item::Data_Bus_Bytes
Definition at line 85 of file axi_seq_item.svh.
Referenced by convert2string(), initialize(), and update().
int axi_seq_item::dataoffset =0
Definition at line 97 of file axi_seq_item.svh.
Referenced by initialize(), axi_monitor::monitor_read_data(), axi_monitor::monitor_write_data(), axi_driver::read_data(), axi_responder::read_data(), and axi_driver::write_data().
int axi_seq_item::dtsize
Definition at line 93 of file axi_seq_item.svh.
Referenced by convert2string(), and initialize().
int axi_seq_item::initialized =0
Definition at line 98 of file axi_seq_item.svh.
Referenced by initialize().
int axi_seq_item::iNumber_Bytes
Definition at line 83 of file axi_seq_item.svh.
Referenced by convert2string(), and update().
rand int axi_seq_item::len =0
Definition at line 48 of file axi_seq_item.svh.
Referenced by ar_from_class(), aw_from_class(), axi_seq::body(), convert2string(), data_c(), do_compare(), do_copy(), initialize(), axi_monitor::monitor_read_address(), axi_monitor::monitor_read_data(), axi_monitor::monitor_write_address(), axi_monitor::monitor_write_data(), post_randomize(), axi_driver::read_data(), valid_c(), wlast_c(), and wstrb_c().
logic<0:0> axi_seq_item::lock = 0x0
Definition at line 55 of file axi_seq_item.svh.
Referenced by do_copy().
int axi_seq_item::Lower_Byte_Lane
Definition at line 89 of file axi_seq_item.svh.
Referenced by convert2string(), axi_monitor::monitor_read_data(), axi_monitor::monitor_write_data(), axi_driver::read_data(), axi_responder::read_data(), update(), and axi_driver::write_data().
bit<63:0> axi_seq_item::Lower_Wrap_Boundary
Definition at line 87 of file axi_seq_item.svh.
Referenced by convert2string(), initialize(), and update_address().
bit<1:0> axi_seq_item::Mode
Definition at line 91 of file axi_seq_item.svh.
Referenced by convert2string(), initialize(), and update_address().
int axi_seq_item::n =0
Definition at line 94 of file axi_seq_item.svh.
int axi_seq_item::Number_Bytes
Definition at line 82 of file axi_seq_item.svh.
Referenced by convert2string(), initialize(), update(), and update_address().
logic<2:0> axi_seq_item::prot = 0x0
Definition at line 57 of file axi_seq_item.svh.
Referenced by do_copy().
logic<3:0> axi_seq_item::qos = 0x0
Definition at line 58 of file axi_seq_item.svh.
Referenced by do_copy().
bit<63:0> axi_seq_item::Start_Address
Definition at line 79 of file axi_seq_item.svh.
Referenced by axi_seq::body(), convert2string(), initialize(), and axi_monitor::monitor_write_data().
rand logic<31:0> axi_seq_item::toggle_pattern = 0xFFFF_FFFF
Definition at line 65 of file axi_seq_item.svh.
Referenced by axi_responder::run_phase().
int axi_seq_item::Upper_Byte_Lane
Definition at line 90 of file axi_seq_item.svh.
Referenced by convert2string(), axi_monitor::monitor_read_data(), axi_monitor::monitor_write_data(), axi_driver::read_data(), axi_responder::read_data(), update(), and axi_driver::write_data().
bit<63:0> axi_seq_item::Upper_Wrap_Boundary
Definition at line 88 of file axi_seq_item.svh.
Referenced by convert2string(), initialize(), and update_address().
rand bit axi_seq_item::valid[]
Definition at line 41 of file axi_seq_item.svh.
Referenced by do_copy(), initialize(), post_randomize(), valid_c(), and axi_driver::write_data().
int axi_seq_item::validcntr
Definition at line 95 of file axi_seq_item.svh.
Referenced by initialize(), axi_responder::read_data(), and axi_driver::write_data().
int axi_seq_item::validcntr_max
Definition at line 96 of file axi_seq_item.svh.
Referenced by initialize(), axi_responder::read_data(), and axi_driver::write_data().
rand bit axi_seq_item::wlast[]
Definition at line 47 of file axi_seq_item.svh.
Referenced by do_copy(), post_randomize(), w_from_class(), and wlast_c().
rand bit axi_seq_item::wstrb[]
Definition at line 46 of file axi_seq_item.svh.
Referenced by do_copy(), axi_monitor::monitor_write_data(), post_randomize(), w_from_class(), wlast_c(), and wstrb_c().
The documentation for this class was generated from the following file:
tb/axi_seq_item.svh