AXI muckbucket: axi_driver Class Reference
axi_driver Class Reference
Public Member Functions
uvm_component_utils (axi_driver) axi_if_abstract vif
new (string name="axi_driver", uvm_component parent=null)
void build_phase (uvm_phase phase)
void connect_phase (uvm_phase phase)
void end_of_elaboration_phase (uvm_phase phase)
task run_phase (uvm_phase phase)
task driver_write_address ()
task driver_write_data ()
task driver_write_response ()
task driver_read_address ()
task driver_read_data ()
task responder_write_address ()
task responder_write_data ()
task responder_write_response ()
task responder_read_address ()
task responder_read_data ()
Public Attributes
axi_agent_config m_config
memory m_memory
mailbox< axi_seq_item > driver_writeaddress_mbx = new(0)
mailbox< axi_seq_item > driver_writedata_mbx = new(0)
mailbox< axi_seq_item > driver_writeresponse_mbx = new(0)
mailbox< axi_seq_item > driver_readaddress_mbx = new(0)
mailbox< axi_seq_item > driver_readdata_mbx = new(0)
mailbox< axi_seq_item > responder_readaddress_mbx = new(0)
mailbox< axi_seq_item > responder_readdata_mbx = new(0)
mailbox< axi_seq_item > responder_writeaddress_mbx = new(0)
mailbox< axi_seq_item > responder_writedata_mbx = new(0)
mailbox< axi_seq_item > responder_writeresponse_mbx = new(0)
reg foo
int min_clks_between_aw_transfers =0
int max_clks_between_aw_transfers =0
int min_clks_between_w_transfers =0
int max_clks_between_w_transfers =0
int min_clks_between_b_transfers =0
int max_clks_between_b_transfers =0
bit axi_incompatible_awready_toggling_mode =0
bit axi_incompatible_wready_toggling_mode =0
bit axi_incompatible_bready_toggling_mode =0
int min_clks_between_ar_transfers =0
int max_clks_between_ar_transfers =0
int min_clks_between_r_transfers =0
int max_clks_between_r_transfers =0
bit axi_incompatible_rready_toggling_mode =0
Detailed Description
Definition at line 29 of file axi_driver.svh.
Member Function Documentation
void axi_driver::build_phase (uvm_phase phase)
Definition at line 121 of file axi_driver.svh.
void axi_driver::connect_phase (uvm_phase phase)
Definition at line 128 of file axi_driver.svh.
task axi_driver::driver_read_address ()
Definition at line 469 of file axi_driver.svh.
References axi_seq_item::addr, axi_seq_item::ar_from_class(), axi_seq_item_ar_vector_s::araddr, axi_seq_item_ar_vector_s::arburst, axi_seq_item_ar_vector_s::arid, axi_seq_item_ar_vector_s::arlen, axi_seq_item_ar_vector_s::arsize, axi_seq_item::burst_size, axi_seq_item::calculate_aligned_address(), axi_seq_item::calculate_beats(), driver_readaddress_mbx, driver_readdata_mbx, axi_seq_item::len, max_clks_between_ar_transfers, and min_clks_between_ar_transfers.
Referenced by run_phase().
task axi_driver::driver_read_data ()
Definition at line 549 of file axi_driver.svh.
References axi_seq_item::convert2string(), axi_seq_item::data, axi_seq_item::dataoffset, driver_readdata_mbx, axi_seq_item::initialize(), axi_seq_item::len, axi_seq_item::Lower_Byte_Lane, m_config, axi_seq_item_r_vector_s::rdata, axi_seq_item_r_vector_s::rlast, axi_agent_config::rready_toggle_pattern, axi_seq_item::update_address(), and axi_seq_item::Upper_Byte_Lane.
Referenced by run_phase().
task axi_driver::driver_write_address ()
Definition at line 230 of file axi_driver.svh.
References axi_seq_item::addr, axi_seq_item::aw_from_class(), axi_seq_item_aw_vector_s::awaddr, axi_seq_item_aw_vector_s::awburst, axi_seq_item_aw_vector_s::awid, axi_seq_item_aw_vector_s::awlen, axi_seq_item_aw_vector_s::awsize, axi_seq_item::burst_size, axi_seq_item::calculate_aligned_address(), axi_seq_item::calculate_beats(), driver_writeaddress_mbx, driver_writedata_mbx, axi_seq_item::len, max_clks_between_aw_transfers, and min_clks_between_aw_transfers.
Referenced by run_phase().
task axi_driver::driver_write_data ()
Definition at line 323 of file axi_driver.svh.
References axi_incompatible_wready_toggling_mode, axi_seq_item::Burst_Length_Bytes, axi_seq_item::data, axi_seq_item::dataoffset, driver_writedata_mbx, driver_writeresponse_mbx, axi_seq_item::initialize(), axi_seq_item::Lower_Byte_Lane, max_clks_between_w_transfers, min_clks_between_w_transfers, axi_seq_item::update_address(), axi_seq_item::Upper_Byte_Lane, axi_seq_item::valid, axi_seq_item::validcntr, axi_seq_item::validcntr_max, axi_seq_item_w_vector_s::wdata, axi_seq_item_w_vector_s::wlast, axi_seq_item_w_vector_s::wstrb, and axi_seq_item_w_vector_s::wvalid.
Referenced by run_phase().
task axi_driver::driver_write_response ()
Definition at line 445 of file axi_driver.svh.
References axi_seq_item::bid, axi_seq_item_b_vector_s::bid, axi_agent_config::bready_toggle_pattern, axi_seq_item::bresp, axi_seq_item_b_vector_s::bresp, driver_writeresponse_mbx, and m_config.
Referenced by run_phase().
void axi_driver::end_of_elaboration_phase (uvm_phase phase)
Definition at line 132 of file axi_driver.svh.
axi_driver::new (string name = "axi_driver", uvm_component parent = null)
Definition at line 114 of file axi_driver.svh.
task axi_driver::responder_read_address ()
Definition at line 743 of file axi_driver.svh.
Referenced by run_phase().
task axi_driver::responder_read_data ()
Definition at line 747 of file axi_driver.svh.
References axi_incompatible_rready_toggling_mode, axi_seq_item::Burst_Length_Bytes, axi_seq_item::data, axi_seq_item::dataoffset, axi_seq_item::initialize(), axi_seq_item::Lower_Byte_Lane, max_clks_between_r_transfers, min_clks_between_r_transfers, axi_seq_item_r_vector_s::rdata, responder_readdata_mbx, axi_seq_item_r_vector_s::rid, axi_seq_item_r_vector_s::rlast, axi_seq_item_r_vector_s::rvalid, axi_seq_item::update_address(), axi_seq_item::Upper_Byte_Lane, axi_seq_item::validcntr, and axi_seq_item::validcntr_max.
Referenced by run_phase().
task axi_driver::responder_write_address ()
Definition at line 597 of file axi_driver.svh.
References axi_seq_item::aw_to_class(), axi_seq_item::data, axi_seq_item::len, responder_writeaddress_mbx, responder_writedata_mbx, axi_seq_item::wlast, and axi_seq_item::wstrb.
Referenced by run_phase().
task axi_driver::responder_write_data ()
Definition at line 620 of file axi_driver.svh.
References foo, responder_writedata_mbx, and responder_writeresponse_mbx.
Referenced by run_phase().
task axi_driver::responder_write_response ()
Definition at line 672 of file axi_driver.svh.
References axi_seq_item_b_vector_s::bid, axi_seq_item_b_vector_s::bresp, driver_writeresponse_mbx, max_clks_between_b_transfers, min_clks_between_b_transfers, and responder_writeresponse_mbx.
Referenced by run_phase().
task axi_driver::run_phase (uvm_phase phase)
Definition at line 136 of file axi_driver.svh.
References axi_seq_item::cmd, axi_seq_item::convert2string(), driver_read_address(), driver_read_data(), driver_readaddress_mbx, driver_write_address(), driver_write_data(), driver_write_response(), driver_writeaddress_mbx, axi_agent_config::drv_type, e_DRIVER, e_READ, e_READ_DATA, e_RESPONDER, e_SETARREADYTOGGLEPATTERN, e_SETAWREADYTOGGLEPATTERN, e_SETWREADYTOGGLEPATTERN, e_WRITE, m_config, responder_read_address(), responder_read_data(), responder_readdata_mbx, responder_write_address(), responder_write_data(), responder_write_response(), responder_writeaddress_mbx, and axi_seq_item::toggle_pattern.
axi_driver::uvm_component_utils (axi_driver)
Member Data Documentation
bit axi_driver::axi_incompatible_awready_toggling_mode =0
Definition at line 98 of file axi_driver.svh.
bit axi_driver::axi_incompatible_bready_toggling_mode =0
Definition at line 100 of file axi_driver.svh.
bit axi_driver::axi_incompatible_rready_toggling_mode =0
Definition at line 110 of file axi_driver.svh.
Referenced by responder_read_data().
bit axi_driver::axi_incompatible_wready_toggling_mode =0
Definition at line 99 of file axi_driver.svh.
Referenced by driver_write_data().
mailbox<axi_seq_item> axi_driver::driver_readaddress_mbx = new(0)
Definition at line 40 of file axi_driver.svh.
Referenced by driver_read_address(), and run_phase().
mailbox<axi_seq_item> axi_driver::driver_readdata_mbx = new(0)
Definition at line 41 of file axi_driver.svh.
Referenced by driver_read_address(), and driver_read_data().
mailbox<axi_seq_item> axi_driver::driver_writeaddress_mbx = new(0)
Definition at line 36 of file axi_driver.svh.
Referenced by driver_write_address(), and run_phase().
mailbox<axi_seq_item> axi_driver::driver_writedata_mbx = new(0)
Definition at line 37 of file axi_driver.svh.
Referenced by driver_write_address(), and driver_write_data().
mailbox<axi_seq_item> axi_driver::driver_writeresponse_mbx = new(0)
Definition at line 38 of file axi_driver.svh.
Referenced by driver_write_data(), driver_write_response(), and responder_write_response().
reg axi_driver::foo
Definition at line 82 of file axi_driver.svh.
Referenced by responder_write_data().
axi_agent_config axi_driver::m_config
Definition at line 33 of file axi_driver.svh.
Referenced by axi_agent::build_phase(), driver_read_data(), driver_write_response(), and run_phase().
memory axi_driver::m_memory
Definition at line 34 of file axi_driver.svh.
Referenced by axi_agent::build_phase().
int axi_driver::max_clks_between_ar_transfers =0
Definition at line 105 of file axi_driver.svh.
Referenced by driver_read_address().
int axi_driver::max_clks_between_aw_transfers =0
Definition at line 87 of file axi_driver.svh.
Referenced by driver_write_address().
int axi_driver::max_clks_between_b_transfers =0
Definition at line 93 of file axi_driver.svh.
Referenced by responder_write_response().
int axi_driver::max_clks_between_r_transfers =0
Definition at line 108 of file axi_driver.svh.
Referenced by responder_read_data().
int axi_driver::max_clks_between_w_transfers =0
Definition at line 90 of file axi_driver.svh.
Referenced by driver_write_data().
int axi_driver::min_clks_between_ar_transfers =0
Definition at line 104 of file axi_driver.svh.
Referenced by driver_read_address().
int axi_driver::min_clks_between_aw_transfers =0
Definition at line 86 of file axi_driver.svh.
Referenced by driver_write_address().
int axi_driver::min_clks_between_b_transfers =0
Definition at line 92 of file axi_driver.svh.
Referenced by responder_write_response().
int axi_driver::min_clks_between_r_transfers =0
Definition at line 107 of file axi_driver.svh.
Referenced by responder_read_data().
int axi_driver::min_clks_between_w_transfers =0
Definition at line 89 of file axi_driver.svh.
Referenced by driver_write_data().
mailbox<axi_seq_item> axi_driver::responder_readaddress_mbx = new(0)
Definition at line 43 of file axi_driver.svh.
mailbox<axi_seq_item> axi_driver::responder_readdata_mbx = new(0)
Definition at line 44 of file axi_driver.svh.
Referenced by responder_read_data(), and run_phase().
mailbox<axi_seq_item> axi_driver::responder_writeaddress_mbx = new(0)
Definition at line 49 of file axi_driver.svh.
Referenced by responder_write_address(), and run_phase().
mailbox<axi_seq_item> axi_driver::responder_writedata_mbx = new(0)
Definition at line 50 of file axi_driver.svh.
Referenced by responder_write_address(), and responder_write_data().
mailbox<axi_seq_item> axi_driver::responder_writeresponse_mbx = new(0)
Definition at line 51 of file axi_driver.svh.
Referenced by responder_write_data(), and responder_write_response().
The documentation for this class was generated from the following file:
tb/axi_driver.svh