AXI muckbucket: axi_responder Class Reference
axi_responder Class Reference
Logic to act as an AXI slave (responder) for all 5 channels.
Public Member Functions
uvm_component_utils (axi_responder) axi_if_abstract vif
new (string name="axi_responder", uvm_component parent=null)
Constructor.
void build_phase (uvm_phase phase)
Creates the virtual interface.
void connect_phase (uvm_phase phase)
Nothing to connect so doesn't actually do anything except call parent connect phase.
task run_phase (uvm_phase phase)
Launches channel responder threads and then acts as a dispatcher.
task write_address ()
Write Address channel thread.
task write_data ()
Write Data channel thread.
task write_response ()
Write Response channel thread.
task read_address ()
Read Address channel thread.
task read_data ()
Read Data channel thread.
Public Attributes
axi_agent_config m_config
memory m_memory
mailbox< axi_seq_item > readaddress_mbx = new(0)
mailbox< axi_seq_item > readdata_mbx = new(0)
mailbox< axi_seq_item > writeaddress_mbx = new(0)
mailbox< axi_seq_item > writedata_mbx = new(0)
mailbox< axi_seq_item > writeresponse_mbx = new(0)
int min_clks_between_b_transfers =0
int max_clks_between_b_transfers =0
bit axi_incompatible_awready_toggling_mode =0
bit axi_incompatible_wready_toggling_mode =0
bit axi_incompatible_bready_toggling_mode =0
int min_clks_between_ar_transfers =0
int max_clks_between_ar_transfers =0
int min_clks_between_r_transfers =0
int max_clks_between_r_transfers =0
bit axi_incompatible_rready_toggling_mode =0
Detailed Description
Logic to act as an AXI slave (responder) for all 5 channels.
Definition at line 23 of file axi_responder.svh.
Member Function Documentation
void axi_responder::build_phase (uvm_phase phase)
Creates the virtual interface.
Definition at line 86 of file axi_responder.svh.
void axi_responder::connect_phase (uvm_phase phase)
Nothing to connect so doesn't actually do anything except call parent connect phase.
Definition at line 95 of file axi_responder.svh.
axi_responder::new (string name = "axi_responder", uvm_component parent = null)
Constructor.
Doesn't actually do anything except call parent constructor
Definition at line 81 of file axi_responder.svh.
task axi_responder::read_address ()
Read Address channel thread.
Does nothing. The monitor handles taking AXI read data transfers and creating a read data packet that gets sent to the read data channel thread.
Definition at line 313 of file axi_responder.svh.
Referenced by run_phase().
task axi_responder::read_data ()
Read Data channel thread.
Deassert rvalid
wait for tlm packet (responder packet from axi_monitor)
loop through data
if ready and valid, wait X clocks where x>=0, then check for any more queued items
if avail, then fetch and goto 'Loop through data' step.
if no items to be driven on next clk, drive all read data signals low and goto 'Wait for TLM item in mailbox' step.
Definition at line 326 of file axi_responder.svh.
References axi_incompatible_rready_toggling_mode, axi_seq_item::Burst_Length_Bytes, axi_seq_item::data, axi_seq_item::dataoffset, axi_seq_item::initialize(), axi_seq_item::Lower_Byte_Lane, max_clks_between_r_transfers, min_clks_between_r_transfers, axi_seq_item_r_vector_s::rdata, readdata_mbx, axi_seq_item_r_vector_s::rid, axi_seq_item_r_vector_s::rlast, axi_seq_item_r_vector_s::rvalid, axi_seq_item::update_address(), axi_seq_item::Upper_Byte_Lane, axi_seq_item::validcntr, and axi_seq_item::validcntr_max.
Referenced by run_phase().
task axi_responder::run_phase (uvm_phase phase)
Launches channel responder threads and then acts as a dispatcher.
After launching 5 different threads (one for each channel), this task acts as a dispatcher. It waits for TLM packets and then stuffs them into the appropriate thread's mailbox. IE: If it's an AXI write packet then it puts the packet into the write_address's mailbox so it can handle it. It the waits for the next TLM packet. NOTE: it does not wait for the other thread to finish processing the packet, it just puts it in the mailbox and then immediately waits for the next packet.
Definition at line 109 of file axi_responder.svh.
References axi_seq_item::cmd, axi_seq_item::convert2string(), e_READ_DATA, e_SETARREADYTOGGLEPATTERN, e_SETAWREADYTOGGLEPATTERN, e_SETWREADYTOGGLEPATTERN, e_WRITE, read_address(), read_data(), readdata_mbx, axi_seq_item::toggle_pattern, write_address(), write_data(), write_response(), and writeaddress_mbx.
axi_responder::uvm_component_utils (axi_responder)
task axi_responder::write_address ()
Write Address channel thread.
Actually does almost nothing. The monitor handles taking AXI write data and storing it into memory and loadable logic in the axi_if handles awready. This task is basically part of a chain that guarantees that a write response won't be sent back before both write address and write data have been received.
Todo:
: clean up this task. Destroy that chain.
Definition at line 162 of file axi_responder.svh.
References writeaddress_mbx, and writedata_mbx.
Referenced by run_phase().
task axi_responder::write_data ()
Write Data channel thread.
Actually does almost nothing. The monitor handles taking AXI write data and storing it into memory and loadable logic in the axi_if handles awready. This task is basically part of a chain that guarantees that a write response won't be sent back before both write address and write data have been received.
Todo:
: clean up this task. Destroy that chain.
Definition at line 192 of file axi_responder.svh.
References axi_seq_item::convert2string(), axi_seq_item_w_vector_s::wlast, writedata_mbx, and writeresponse_mbx.
Referenced by run_phase().
task axi_responder::write_response ()
Write Response channel thread.
Deassert bvalid
Wait for TLM item in mailbox
Initialize variables
Write out
if ready and valid, wait X clocks where x>=0, then check for any more queued items
if avail, then fetch and goto 'Initialize variables' step.
if no items to be driven on next clk, drive all write response signals low and goto 'Wait for TLM item in mailbox' step. \todo: response values are hardcoded. Get from response seq?
Definition at line 232 of file axi_responder.svh.
References axi_seq_item_b_vector_s::bid, axi_seq_item_b_vector_s::bresp, axi_seq_item::convert2string(), max_clks_between_b_transfers, min_clks_between_b_transfers, and writeresponse_mbx.
Referenced by run_phase().
Member Data Documentation
bit axi_responder::axi_incompatible_awready_toggling_mode =0
Definition at line 62 of file axi_responder.svh.
bit axi_responder::axi_incompatible_bready_toggling_mode =0
Definition at line 64 of file axi_responder.svh.
bit axi_responder::axi_incompatible_rready_toggling_mode =0
Definition at line 74 of file axi_responder.svh.
Referenced by read_data().
bit axi_responder::axi_incompatible_wready_toggling_mode =0
Definition at line 63 of file axi_responder.svh.
axi_agent_config axi_responder::m_config
Definition at line 27 of file axi_responder.svh.
Referenced by axi_agent::build_phase().
memory axi_responder::m_memory
Definition at line 28 of file axi_responder.svh.
Referenced by axi_agent::build_phase().
int axi_responder::max_clks_between_ar_transfers =0
Definition at line 69 of file axi_responder.svh.
int axi_responder::max_clks_between_b_transfers =0
Definition at line 57 of file axi_responder.svh.
Referenced by write_response().
int axi_responder::max_clks_between_r_transfers =0
Definition at line 72 of file axi_responder.svh.
Referenced by read_data().
int axi_responder::min_clks_between_ar_transfers =0
Definition at line 68 of file axi_responder.svh.
int axi_responder::min_clks_between_b_transfers =0
Definition at line 56 of file axi_responder.svh.
Referenced by write_response().
int axi_responder::min_clks_between_r_transfers =0
Definition at line 71 of file axi_responder.svh.
Referenced by read_data().
mailbox<axi_seq_item> axi_responder::readaddress_mbx = new(0)
Definition at line 30 of file axi_responder.svh.
mailbox<axi_seq_item> axi_responder::readdata_mbx = new(0)
Definition at line 31 of file axi_responder.svh.
Referenced by read_data(), and run_phase().
mailbox<axi_seq_item> axi_responder::writeaddress_mbx = new(0)
Definition at line 36 of file axi_responder.svh.
Referenced by run_phase(), and write_address().
mailbox<axi_seq_item> axi_responder::writedata_mbx = new(0)
Definition at line 37 of file axi_responder.svh.
Referenced by write_address(), and write_data().
mailbox<axi_seq_item> axi_responder::writeresponse_mbx = new(0)
Definition at line 38 of file axi_responder.svh.
Referenced by write_data(), and write_response().
The documentation for this class was generated from the following file:
tb/axi_responder.svh