AXI muckbucket: axi_seq Class Reference
axi_seq Class Reference
Writes to memory over AXI, backdoor readback, then AXI readback.
Public Member Functions
uvm_object_utils (axi_seq) const int axi_readback
new (string name="axi_seq")
Constructor.
task body ()
Does all the work.
void response_handler (uvm_sequence_item response)
bit initialize ()
Make sure addr_width,data_width, etc are set.
void set_addr_width (int width=0)
Set Address bus width.
void set_data_width (int width=0)
Set Data bus width.
void set_id_width (int width=0)
Set ID vector width.
void set_len_width (int width=0)
Set length vector width.
bit compare_items (ref axi_seq_item write_item, ref axi_seq_item read_item)
bit check_memory (ref axi_seq_item item, input bit< 63:0 > lower_addr, input bit< 63:0 > upper_addr)
uvm_object_utils (axi_seq) const int axi_readback
new (string name="axi_seq")
task body ()
void response_handler (uvm_sequence_item response)
bit initialize ()
void set_addr_width (int width=0)
void set_data_width (int width=0)
void set_id_width (int width=0)
void set_len_width (int width=0)
bit compare_items (ref axi_seq_item write_item, ref axi_seq_item read_item)
bit check_memory (ref axi_seq_item item, input bit< 63:0 > lower_addr, input bit< 63:0 > upper_addr)
uvm_object_utils (axi_seq) const int axi_readback
new (string name="axi_seq")
task body ()
void response_handler (uvm_sequence_item response)
void set_data_width (int width=0)
void set_id_width (int width=0)
void set_len_width (int width=0)
bit compare_items (ref axi_seq_item write_item, ref axi_seq_item read_item)
bit check_memory (ref axi_seq_item item, input bit< ADDR_WIDTH-1:0 > lower_addr, input bit< ADDR_WIDTH-1:0 > upper_addr)
Public Attributes
const int clearmemory = 0
const int postcheck = 0
const int precheck = 0
const int window_size = 0x1000
const int xfers_to_send = 3
const int pipelined_bursts_enabled =0
int addr_width =0
int data_width =0
int id_width =0
int len_width =0
int xfers_done =0
memory m_memory
axi_seq_item write_item []
axi_seq_item read_item []
event writes_done
Detailed Description
Writes to memory over AXI, backdoor readback, then AXI readback.
miscompares are flagged.
Definition at line 25 of file axi_pipelined_writes_seq.svh.
Member Function Documentation
task axi_seq::body ()
task axi_seq::body ()
Does all the work.
Creates constrained random AXI write packet
Sends it
Backdoor read of memory to verify correctly written
Creates constrained random AXI read packet with same len and address as write packet
Sends it
Verifies read back data with written data.
two modes: Serial, Write_addr, then write, then resp. Repeat Parallel - Multiple write_adr, then multiple write_data, then multiple resp, repeat
Definition at line 234 of file axi_pipelined_writes_seq.svh.
References axi_seq_item::addr, axi_seq_item::burst_size, axi_seq_item::burst_type, check_memory(), clearmemory, compare_items(), data_width, e_READ, e_WRITE, axi_seq_item::id, initialize(), axi_seq_item::len, m_memory, pipelined_bursts_enabled, axi_seq_item::protocol, read_item, window_size, memory::write(), write_item, writes_done, xfers_done, and xfers_to_send.
task axi_seq::body ()
automatic bit axi_seq::check_memory (ref axi_seq_item item, input bit< ADDR_WIDTH-1:0 > lower_addr, input bit< ADDR_WIDTH-1:0 > upper_addr)
Definition at line 398 of file axi_seq.svh.
References ADDR_WIDTH, calculate_axlen(), compare_items(), e_FIXED, e_INCR, e_WRAP, and memory::read().
bit axi_seq::check_memory (ref axi_seq_item item, input bit< 63:0 > lower_addr, input bit< 63:0 > upper_addr)
Definition at line 378 of file axi_pipelined_writes_seq.svh.
References calculate_axlen(), e_FIXED, e_INCR, e_WRAP, m_memory, postcheck, precheck, and memory::read().
Referenced by body().
bit axi_seq::check_memory (ref axi_seq_item item, input bit< 63:0 > lower_addr, input bit< 63:0 > upper_addr)
bit axi_seq::compare_items (ref axi_seq_item write_item, ref axi_seq_item read_item)
bit axi_seq::compare_items (ref axi_seq_item write_item, ref axi_seq_item read_item)
bit axi_seq::compare_items (ref axi_seq_item write_item, ref axi_seq_item read_item)
........................
Definition at line 669 of file axi_pipelined_writes_seq.svh.
References e_FIXED, e_INCR, and e_WRAP.
Referenced by body(), check_memory(), and response_handler().
bit axi_seq::initialize ()
bit axi_seq::initialize ()
Make sure addr_width,data_width, etc are set.
if they are not, then try to fetch them from config db. if unable, then fail.
Returns
true if success, false if fail
Definition at line 170 of file axi_pipelined_writes_seq.svh.
References addr_width, data_width, id_width, len_width, and m_memory.
Referenced by body().
axi_seq::new (string name = "axi_seq")
axi_seq::new (string name = "axi_seq")
Constructor.
Doesn't actually do anything except call parent constructor
Definition at line 120 of file axi_pipelined_writes_seq.svh.
axi_seq::new (string name = "axi_seq")
void axi_seq::response_handler (uvm_sequence_item response)
void axi_seq::response_handler (uvm_sequence_item response)
Definition at line 79 of file axi_pipelined_writes_seq.svh.
References axi_seq_item::cmd, compare_items(), axi_seq_item::convert2string(), e_READ_DATA, e_WRITE_RESPONSE, axi_seq_item::id, read_item, write_item, xfers_done, and xfers_to_send.
void axi_seq::response_handler (uvm_sequence_item response)
void axi_seq::set_addr_width (int width = 0)
void axi_seq::set_addr_width (int width = 0)
Set Address bus width.
AXI supports multiple bus widths, parameterized at runtime. We have to tell the sequence so we can randomize accordingly. IE: If the addr bus width is 32, don't try to use 64 bits.
Definition at line 130 of file axi_pipelined_writes_seq.svh.
References addr_width.
void axi_seq::set_data_width (int width = 0)
void axi_seq::set_data_width (int width = 0)
void axi_seq::set_data_width (int width = 0)
Set Data bus width.
Set Address bus width.
AXI supports multiple bus widths, parameterized at runtime. We have to tell the sequence so we can randomize accordingly. IE: If the data bus width is 32, don't send a burst_size=64bits.
AXI supports multiple bus widths, parameterized at runtime. We have to tell the sequence so we can randomize accordingly. IE: If the addr bus width is 32, don't try to use 64 bits.
Set Data bus width
AXI supports multiple bus widths, parameterized at runtime. We have to tell the sequence so we can randomize accordingly. IE: If the data bus width is 32, don't send a burst_size=64bits.
Definition at line 140 of file axi_pipelined_writes_seq.svh.
References data_width.
void axi_seq::set_id_width (int width = 0)
void axi_seq::set_id_width (int width = 0)
Set ID vector width.
AXI supports ID widths, parameterized at runtime. We have to tell the sequence so we can randomize accordingly.
Definition at line 149 of file axi_pipelined_writes_seq.svh.
References id_width.
void axi_seq::set_id_width (int width = 0)
void axi_seq::set_len_width (int width = 0)
void axi_seq::set_len_width (int width = 0)
void axi_seq::set_len_width (int width = 0)
Set length vector width.
AXI supports 2 different AxLEN widths, parameterized at runtime. 4-bit and 8-bit. We have to tell the sequence so we can randomize accordingly.
Definition at line 160 of file axi_pipelined_writes_seq.svh.
References len_width.
axi_seq::uvm_object_utils (axi_seq) const
axi_seq::uvm_object_utils (axi_seq) const
axi_seq::uvm_object_utils (axi_seq) const
Member Data Documentation
int axi_seq::addr_width =0
Definition at line 40 of file axi_pipelined_writes_seq.svh.
Referenced by initialize(), and set_addr_width().
const int axi_seq::clearmemory = 0
Definition at line 30 of file axi_pipelined_writes_seq.svh.
Referenced by body().
int axi_seq::data_width =0
Definition at line 41 of file axi_pipelined_writes_seq.svh.
Referenced by body(), initialize(), and set_data_width().
int axi_seq::id_width =0
Definition at line 42 of file axi_pipelined_writes_seq.svh.
Referenced by initialize(), and set_id_width().
int axi_seq::len_width =0
Definition at line 43 of file axi_pipelined_writes_seq.svh.
Referenced by initialize(), and set_len_width().
memory axi_seq::m_memory
Definition at line 46 of file axi_pipelined_writes_seq.svh.
Referenced by body(), check_memory(), and initialize().
const int axi_seq::pipelined_bursts_enabled =0
Definition at line 36 of file axi_pipelined_writes_seq.svh.
Referenced by body().
const int axi_seq::postcheck = 0
Definition at line 31 of file axi_pipelined_writes_seq.svh.
Referenced by check_memory().
const int axi_seq::precheck = 0
Definition at line 32 of file axi_pipelined_writes_seq.svh.
Referenced by check_memory().
axi_seq_item axi_seq::read_item
Definition at line 49 of file axi_pipelined_writes_seq.svh.
Referenced by body(), and response_handler().
const int axi_seq::window_size = 0x1000
Definition at line 33 of file axi_pipelined_writes_seq.svh.
Referenced by body().
axi_seq_item axi_seq::write_item
Definition at line 48 of file axi_pipelined_writes_seq.svh.
Referenced by body(), and response_handler().
event axi_seq::writes_done
Definition at line 54 of file axi_pipelined_writes_seq.svh.
Referenced by body().
int axi_seq::xfers_done =0
Definition at line 44 of file axi_pipelined_writes_seq.svh.
Referenced by body(), and response_handler().
const int axi_seq::xfers_to_send = 3
Definition at line 34 of file axi_pipelined_writes_seq.svh.
Referenced by body(), and response_handler().
The documentation for this class was generated from the following files:
result_from_tec101/tb/tb/axi_pipelined_writes_seq.svh
result_from_tec101/tb/tb/axi_seq.svh