AXI muckbucket: axi_coveragecollector Class Reference
axi_coveragecollector Class Reference
Collects coverage.
Public Member Functions
uvm_component_utils (axi_coveragecollector) covergroup aw_cg with function sample(axi_seq_item item)
covergroup ar_cg with function sample (axi_seq_item item)
new (string name="axi_coveragecollector", uvm_component parent=null)
Constructor.
virtual void write (axi_seq_item t)
covergroup sampling
Detailed Description
Collects coverage.
Write Address and Read Address simple coverage (burst_size, burst_type and awlen)
Definition at line 33 of file axi_coveragecollector.svh.
Member Function Documentation
axi_coveragecollector::new (string name = "axi_coveragecollector", uvm_component parent = null)
Constructor.
allocates covergroups
Definition at line 101 of file axi_coveragecollector.svh.
covergroup ar_cg with function axi_coveragecollector::sample (axi_seq_item item) inline
Definition at line 64 of file axi_coveragecollector.svh.
References axi_seq_item::axlen, axi_seq_item::burst_size, axi_seq_item::burst_type, e_128BYTES, e_16BYTES, e_1BYTE, e_2BYTES, e_32BYTES, e_4BYTES, e_64BYTES, e_8BYTES, e_FIXED, e_INCR, e_WRAP, LEN_WIDTH, and write().
axi_coveragecollector::uvm_component_utils (axi_coveragecollector) inline
Definition at line 35 of file axi_coveragecollector.svh.
References e_128BYTES, e_16BYTES, e_1BYTE, e_2BYTES, e_32BYTES, e_4BYTES, e_64BYTES, e_8BYTES, e_FIXED, e_INCR, e_WRAP, and LEN_WIDTH.
void axi_coveragecollector::write (axi_seq_item t) virtual
covergroup sampling
will update coverage bins, etc.
Definition at line 113 of file axi_coveragecollector.svh.
References axi_seq_item::cmd, axi_seq_item::convert2string(), e_READ, and e_WRITE.
Referenced by sample().
The documentation for this class was generated from the following file:
tb/axi_coveragecollector.svh