AXI muckbucket: memory Class Reference
memory Class Reference
Extremely simple memory model with just write() and read() methods.
Public Member Functions
uvm_component_utils(memory) bit<7 new (string name="memory", uvm_component parent=null)
Constructor.
virtual void write (input bit< ADDR_WIDTH-1:0 > addr, input bit< 7:0 > data)
Writes into memory.
virtual bit< 7:0 > read (input bit< ADDR_WIDTH-1:0 > addr)
Reads from memory.
bit seq_item_check (ref axi_seq_item item, input bit< ADDR_WIDTH-1:0 > lower_addr, input bit< ADDR_WIDTH-1:0 > upper_addr)
Compares an axi_seq_item's data and burst_type against expected matching memory contents.
Detailed Description
Extremely simple memory model with just write() and read() methods.
Definition at line 24 of file memory.svh.
Member Function Documentation
memory::new (string name = "memory", uvm_component parent = null)
Constructor.
Doesn't actually do anything except call parent constructor
Definition at line 43 of file memory.svh.
References new().
Referenced by new().
bit< 7:0 > memory::read (input bit< ADDR_WIDTH-1:0 > addr) virtual
Reads from memory.
uses an associative array. If reading from unwritten address, 'z is returned.
Definition at line 59 of file memory.svh.
Referenced by axi_monitor::read_address(), and seq_item_check().
automatic bit memory::seq_item_check (ref axi_seq_item item, input bit< ADDR_WIDTH-1:0 > lower_addr, input bit< ADDR_WIDTH-1:0 > upper_addr)
Compares an axi_seq_item's data and burst_type against expected matching memory contents.
This function takes into account fixed, incrementing and wrapped burst types. That includes accounting for burst_size.
Definition at line 77 of file memory.svh.
References ADDR_WIDTH, calculate_axlen(), e_FIXED, e_INCR, e_WRAP, and read().
Referenced by axi_sequential_writes_seq::body(), axi_sequential_reads_seq::body(), axi_pipelined_reads_seq::response_handler(), and axi_pipelined_writes_seq::response_handler().
void memory::write (input bit< ADDR_WIDTH-1:0 > addr, input bit< 7:0 > data) virtual
Writes into memory.
Definition at line 50 of file memory.svh.
Referenced by axi_sequential_writes_seq::body(), axi_sequential_reads_seq::body(), axi_pipelined_reads_seq::body(), axi_pipelined_writes_seq::body(), and axi_monitor::write_data().
The documentation for this class was generated from the following file:
tb/memory.svh